apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"

# kubectl taint nodes node1 key1=value1:NoSchedule
# kubectl taint nodes node1 key1=value1:NoExecute
#tolerations:
#- key: "key1"
#  operator: "Equal"
#  value: "value1"
#  effect: "NoSchedule"
#- key: "key1"
#  operator: "Equal"
#  value: "value1"
#  effect: "NoExecute"
